# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # locale: 'en'
    # supported_locales: ['fr', 'en', 'es']
    app.locales: [en, fr]
    translation_dir: '%kernel.project_dir%/translations'
    app.mail_from_adress: 'noreply45@pinter2.com'
    app.mail_from_name: 'Pinter2.45'
    app.file_upload_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    App\Security\Voter\PinVoter:
        autowire: true
        autoconfigure: true
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Entity\Pin:
        autowire: true
        autoconfigure: true

    App\Controller\LanguageController:
        tags: ['controller.service_arguments']

    # App\EventSubscriber\LanguageSubscriber:
    #     arguments:
    #         $requestStack: '@request_stack'
    #     tags:
    #         - { name: kernel.event_subscriber }

    App\Repository\:
        resource: '../src/Repository'
        autowire: true
        tags: ['doctrine.repository_service']